
[functions.execute-weekly-logic]
enabled = true
verify_jwt = true
import_map = "./functions/execute-weekly-logic/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/execute-weekly-logic/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/execute-weekly-logic/*.html" ]

[functions.end-season-and-reset]
enabled = true
verify_jwt = true
import_map = "./functions/end-season-and-reset/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/end-season-and-reset/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/end-season-and-reset/*.html" ]

[functions.check-achievements]
enabled = true
verify_jwt = true
import_map = "./functions/check-achievements/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-achievements/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-achievements/*.html" ]

[functions.process-weekly-quests]
enabled = true
verify_jwt = true
import_map = "./functions/process-weekly-quests/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-weekly-quests/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-weekly-quests/*.html" ]

[functions.impersonate-user]
enabled = true
verify_jwt = true
import_map = "./functions/impersonate-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/impersonate-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/impersonate-user/*.html" ]
